### ISSUE TITLE
Build fails due to missing dependencies

### ISSUE THREAD

**Issue by Ybalrid** [michael-manley/Trinity_ArchLinux_PKGBUILD#1]
Hi, 
I'm trying to build your packages, for fun (and KDE3.5 nostalgia) on a fresh installation of Arch (just with a basic Xorg install with xterm an TWM to see if it works)

tde-tdebase won't build if xscreensaver is not installed, and this package is not present on the "dependencies" of the PKGBUILD.

Since I'm on an empty Arch install, if there's more lacking dependencies I'll report them under this message.

**Comment by Ybalrid** [comment]
Weird, I checked my system and xscreensaver is actually installed. I'm pasting revelent logs here :

makepkg output  : https://gist.github.com/Ybalrid/ed11fa596ec9a8ff0145
CMakeError.log : https://gist.github.com/Ybalrid/4f634792f02ac98989b9
CMakeOutput.log : https://gist.github.com/Ybalrid/ec8cd1d073f520f69a99

**Comment by thx1111** [comment]
Hmm - I'm a bit confused, trying to compare my log file from using "makepkg ... --log" with your linked "makepkg output" file.  They are very different.

Did you completely follow the suggested full build order - 
tqt3 tqtinterface arts dbus-tqt dbus-1-tqt tqca-tls libart-lgpl avahi-tqt tdelibs tdebase?

Your build has:
...
--   tqt-replace path: /bin/tqt-replace
CMake Error at cmake/modules/TDEMacros.cmake:24 (message):
  #################################################

   xscreensaver is requested, but was not found on your system

  #################################################
Call Stack (most recent call first):
  ConfigureChecks.cmake:272 (tde_message_fatal)
  CMakeLists.txt:202 (include)


-- Configuring incomplete, errors occurred!
...

Where my build log has instead:
...
--   tqt-replace path: /usr/bin/tqt-replace
-- Performing Test HAVE_USABLE_TQT
-- Performing Test HAVE_USABLE_TQT - Success
-- checking for 'TDE'
-- Checking for one of the modules 'tqt'
--   found 'TDE', version 14.0.3
...

**Comment by Ybalrid** [comment]
Yeah, I build them in that order. I'm retrying, just to see

**Comment by Ybalrid** [comment]
Nope, I was building it in the correct order and nothing changed. It complains about xscreensaver and abort

**Comment by thx1111** [comment]
Since you are building in a "sparse" Arch install, and my system is a rather "full" install, I would suspect, as you suggested, some missing dependency.

Your CMakeError.log has:

fatal error: X11/extensions/scrnsaver.h: No such file or directory

I have:
$ pacman -Qo /usr/include/X11/extensions/scrnsaver.h
/usr/include/X11/extensions/scrnsaver.h is owned by libxss 1.2.2-2

Do you have the libxss package installed?

**Comment by Ybalrid** [comment]
Okay, the missing package seems to be libxss sice in my CMakeError log the problem seems that ld cannot find "-lXss"

So it seems that the package "libxss" should be added as dependency

**Comment by thx1111** [comment]
May I infer then that installing the libxss package solved the problem?
Note to Michael - tde-tdebase/PKGBUILD, in "makedepends=...", to add:
'libxss'

**Comment by Ybalrid** [comment]
Installing the package solved the problem. I think it works, I'm not sure : 
![ss 2016-03-26 at 03 22 38](https://cloud.githubusercontent.com/assets/1816251/14057506/468bd436-f302-11e5-854d-913c5323675b.jpg)

:-)

**Comment by thx1111** [comment]
Sorry - my mistake.  Package libxss includes the library file /usr/lib/libXss.so.1.0.0, so libxss is a  "depends", not a "makedepends".  But then, you probably noticed that...

**Comment by Ybalrid** [comment]
Yeah, If you see the pull request #3 I added it to the depends. It's dynamicaly link and need the shared object to run

**Comment by Ybalrid** [comment]
I've redone the pull request to avoid conflicts. (#4), I'm waiting for @michael-manley to merge it.

**Comment by Ybalrid** [comment]
It's done, cool!
