### ISSUE TITLE
dbus-core dependency of tde-dbus-tqt does not exist in the official Arch Linux repositories or AUR

### ISSUE THREAD

**Issue by fusion809** [michael-manley/Trinity_ArchLinux_PKGBUILD#11]
Hi,

The `dbus-core` doesn't exist in the official Arch Linux repositories or the AUR. So is this a packaging error or is the `dbus-core` meant to be provided by an unofficial user repository? 

Thanks for your time,
Brenton

**Comment by XorgMC** [comment]
I think dbus-core has been replaced by the dbus package. I just changed it in the PKGBUILD and Trinity works.
