### ISSUE TITLE
Download links are dead

### ISSUE THREAD

**Issue by fusion809** [michael-manley/Trinity_ArchLinux_PKGBUILD#12]
Hi,

I've just tried to use the shell script shown at the ArchWiki to manually compile each R14.0.3 package in this repo and install them, but it failed as this link: http://tde-mirror.yosemite.net/trinity/releases/R14.0.3/dependencies/tqt3-R14.0.3.tar.bz2 is dead. Are there any other more reliable mirrors that can be used?

Thanks for your time,
Brenton

**Comment by XorgMC** [comment]
I've just used Kate to replace all mirror URLs with newer ones:

open a terminal and cd to the R14.0.3 directory. Then open all PKGBUILDs using:
`kate tde-*/PKGBUILD`

Then use the search and replace function to replace all `http://tde-mirror.yosemite.net/trinity/releases/` with the mirror address from official trinity download page, i used `http://ftp.fau.de/trinity/releases/`

Then everything downloaded fine.

**Comment by SlavekB** [comment]
I can recommend you to use redirector: http://mirror.ppa.trinitydesktop.org/trinity/releases/ 
Thanks to this, you should get a result from the nearest functional mirror.

**Comment by michael-manley** [comment]
Today I'll switch all URL's to http://mirror.ppa.trinitydesktop.org/trinity/releases/ 

Thanks for the heads up
