### ISSUE TITLE
Package out of date: 14.0.4 is out as of 7 November 2016

### ISSUE THREAD

**Issue by fusion809** [michael-manley/Trinity_ArchLinux_PKGBUILD#14]
Hi,

14.0.4 is out (which you can confirm by looking at http://trinitydesktop.org/) and is already in official Trinity Debian and Ubuntu repositories, so I just wanted to notify you of this, in case you were unaware and ask that this repository be updated. 

Thanks for your time,
Brenton

**Comment by michael-manley** [comment]
Yes I know about the update. I will create pkgupdates for 14.0.4 soon
