### ISSUE TITLE
tde-tdeartwork doesnt build

### ISSUE THREAD

**Issue by michael-manley** [michael-manley/Trinity_ArchLinux_PKGBUILD#19]
[tde-tdeartwork.txt](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/1113415/tde-tdeartwork.txt)

**Comment by FredBezies** [comment]
Fixed it simply. Just used a make -j1 in build() part. Doesn't like multi-process build.

**Comment by SlavekB** [comment]
That's strange - on Debian / Ubuntu it is successfully built with multi-process (verified with -j20).

**Comment by michael-manley** [comment]
Seems to build fine now with no changes, closing this ticket.
