### ISSUE TITLE
"Nit pick" about language in tde-tqt3/tqt3.install

### ISSUE THREAD

**Issue by thx1111** [michael-manley/Trinity_ArchLinux_PKGBUILD#2]
Very nice Michael!!!  Many thanks for these PKGBUILD files!

To nit-pick, "tde-tqt3/tqt3.install" has:

  echo "In order to update PATH to include TQt3 binaries location, You should"
   echo "reboot your system. Before you do that you can access TQt3 bin path by"
   echo "sourcing /etc/profile.d/tqt3.sh"

I will argue that the system should never ever need to reboot unless a new kernel is being installed or the kernel has encountered a horrible "oops" or has actually crashed.  I assume you meant to suggest that someone might log out and then log back in, if they normally have many many virtual terminals open simultaneously.  Otherwise, it is easy enough to simply re-run ". ~/.bash_profile".  And finally, where you suggest sourcing "/etc/profile.d/tqt3.sh", that alone should be sufficient to rebuild the desired PATH variable on the active terminal.

Perhaps the build note could suggest some action less drastic than a re-boot.

Also, there is 

 echo "renamet to tqt3<toolname> to ensure compatibility with Qt4 and should"

where "renamet" should be "renamed".

**Comment by michael-manley** [comment]
I could remove this, I never noticed a requirement of rebooting as just running the profile scripts is sufficient. These package files were from someone else which i ported to work with R14.0.3.

**Comment by michael-manley** [comment]
I fixed the language on the tqt3 binaries (its actually tq<toolname> not tqt3) also you think just removing that whole part on rebooting and just sourcing in the .install script would work?

**Comment by Ybalrid** [comment]
Yes. Just say to the user that he needs to source the script in /etc/profile.d to get the updated path variables.

**Comment by thx1111** [comment]
Yes, that sounds fine to me.

But then, also consider, there should be a warning about installing these profile.d files and using other Qt-based Desktop Environments, such as LXQt and KDE/Plasma5.  Both the tqt3.sh file, which redefines some "QT" variables, and the trinity.sh file, which redefines some "XDG" variables, *must* be disabled before running either "startlxqt" or "startkde".

Now, I think that that is a bug for both LXQt and KDE, but arguably, it is also a bug for TDE in /opt/trinity/bin/starttde, which does not even attempt to set the "QT" variables.  I am filing a bug report for Trinity.  I don't think LXQt or KDE people are going to be sympathetic, as tqt3.sh and trinity.sh are pretty "heavy-handed".

Also, for the moment, I am suggesting that the contents of both tqt3.sh and trinity.sh be wrapped with, say,

if ps -C starttde,twin &>/dev/null ;then
...
fi

to avoid making angry users, who might "toy" with TDE, and then try to go back to their KDE Desktops, which would then be utterly broken!

Perhaps you would consider adding that wrapping as an Arch patch from the PKGBUILD?

**Comment by thx1111** [comment]
Or, could that be

if ps -C starttde,starttrinity &>/dev/null;then
...
fi

to cover graphical display managers?

**Comment by thx1111** [comment]
Ok, I just embarrassed myself, filing a bug report at Trinity about these /etc/profile.d files.  They are not part of the Trinity source, but have been added with the Arch PKGBUILD files.  It may be that they should be removed?  Or, we should figure-out why they are there.  They are causing a compatibility problem.

Do you know if there is any version control history with these build files?  Where did they come from?

**Comment by Ybalrid** [comment]
Well, they are there to set/update environement variables and they should not cause compatibility issues (well, maybe the QTPATH one...)

If you build TDE by hand from source they ask you to set a bunch of variables too I think.

And these files are made by the PKGBUILD itself with a bunch of "echo "" >> file"

**Comment by thx1111** [comment]
While working with tdebindings, I notice that the PKGBUILD file has
 [ "$QTDIR" = "" ] && . /etc/profile.d/tqt3.sh
 [ "$TDEDIR" = "" ] && . /etc/profile.d/trinity.sh

I'm thinking that these profile.d files were just meant to set-up the environment variables for the build environment.  If so, they should have been explicitly included in the PKGBUILD, and not installed in /etc/profile.d.

Also, if those files *are* wrapped as I suggested with "if ps -C starttde,starttrinity &>/dev/null;then...fi", the PKGBUILD, as is, will fail to source the environment variables, and the build will fail.  So wrapping these files is *not* a solution to anything.

At the moment, I would suggest *not* installing these profile.d files and then modifying all the associated PKGBUILD files in include the contents of these files explicitly, where necessary.
