### ISSUE TITLE
'tde-tqt3' does, strictly, NOT provide 'qt3', and  claiming so breaks dependencies.

### ISSUE THREAD

**Issue by felixbecker2** [michael-manley/Trinity_ArchLinux_PKGBUILD#26]
The package `tde-tqt3` claims to provide the package `qt3`.

This provides-entry should be removed, since it is not completely true and breaks some use cases.

There are packages out there -- e.g. `aur/icewm-utils` -- which (make)depend on `qt3`. And, for example, `tde-tqt3` does not provide the executable `qmake-qt3` (it provides `/opt/trinity/tqt3/bin/qmake`, but this does not yield give `qmake-qt3` without manual intervention).

Other, deeper example, concerns Qt3's version of `qaccel.h`. `tde-tqt3` has the file `/opt/trinity/tqt3/include/ntqaccel.h`. Wanting to build packages which require `qt3` to be compilable and compatible with `tde-tqt3` means a lot of rewriting.

So, provides=`qt3` is not justified. Please remove.

There is a package `aur/qt3`, which can be installed in parallel with `tde-tqt3`, and which fulfills all the `qt3`-dependencies nicely.

I have not checked other issues with maybe other packages.

Maybe all the trinity-stuff needs to be somehow "self-contained", and not claiming to provide some vanilla Qt3-stuff.

Cf. comment at
http://aur.archlinux.org/packages/icewm-utils/#comment-630933 from
2018-01-27.

**Comment by michael-manley** [comment]
Thank you for reporting this issue.

I have fixed the issue and will be uploading this fix to the repos. Most of these PKGBUILDs were written for a older version and was just ported. I am guessing in an older version the Qt3 provided was the same, but seems now its far off where the provides = qt3 is no longer necessary and is erroneous

**Comment by felixbecker2** [comment]
@michael-manley: Thanks. Btw., since I find no other way to contact you but I want to inform you that there is a problem with your Email addres:

You provided your contact as your Email address at http://github.com/michael-manley and at http://wiki.archlinux.org/index.php/unofficial_user_repositories#trinity. But there is some misconfiguration. My `postfix`, which tries to deliver the email via GMX, cannot deliver it and gives me the following error message from GMX:

    (host mail.gmx.net[212.227.17.190] said: 550-Requested action not taken: mailbox unavailable 550 invalid DNS MX or A/AAAA resource record (in reply to RCPT TO command))

Also, trying to access your website http://www.nasutek.org/, which you listed at http://github.com/michael-manley, cannot be reached. No IP address could be resolved (http://nasutek.com/ resolves, but goes to a Typo3 error page.)

**Comment by michael-manley** [comment]
@felixbecker2 Yes thank you for bringing to my attention

Odd that my website still shows nasutek.org, its been .com for a while. Also I know the page shows an error as im recoding it

I should have my email server back up soon, but it is known. again thank you

**Comment by michael-manley** [comment]
@felixbecker2 and anyone else

Email is back, so feel free to send me anything if needed.
