### ISSUE TITLE
glibc-2.27.2 doesn't have header files in /usr/include/rpc/ which breaks trinity install 

### ISSUE THREAD

**Issue by kenshen112** [michael-manley/Trinity_ArchLinux_PKGBUILD#32]
Arch bug report: https://bugs.archlinux.org/task/58414

`In file included from dialogs/qprintdialog.cpp:75:
/usr/include/rpcsvc/yp_prot.h:10:10: fatal error: rpc/rpc.h: No such file or directory
 #include <rpc/rpc.h>
          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:10985: .obj/release-shared-mt/qprintdialog.o] Error 1
make[1]: Leaving directory '/home/kenshen/Desktop/trinity/R14.0.4/tde-tqt3/src/dependencies/tqt3/src'
make: *** [Makefile:40: sub-src] Error 2
` Console output from Trinity build 

in this page https://aur.archlinux.org/packages/qt3/ a suggested fix is:
So I added the line :

   -I/usr/include/tirpc \

to ./configure, and it builds fine.

```

**Comment by michael-manley** [comment]
I did fix this on building R14.0.5, but I might end up backporting that commit as its better then -I method that was used on rpc patches.
