### ISSUE TITLE
Arch packages out of date. R14.0.5 is out.

### ISSUE THREAD

**Issue by mikedebian** [michael-manley/Trinity_ArchLinux_PKGBUILD#35]
According to their homepage.

2018.08.18: Trinity Desktop Environment R14.0.5 Released!

**Comment by michael-manley** [comment]
I was very late on noticing this, as I don't use Arch as much, but I'm in the progress of porting over 14.0.4 PKGBUILDs to 14.0.5, should be out in a few days.
