### ISSUE TITLE
Some packages wont compile

### ISSUE THREAD

**Issue by michael-manley** [michael-manley/Trinity_ArchLinux_PKGBUILD#37]
Listed are some packages that did not compile. Any help needed.

* [tde-tdeartwork-14.0.5-1-x86_64-build.log](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/2818867/tde-tdeartwork-14.0.5-1-x86_64-build.log)
* [tde-amarok-14.0.5-1-x86_64-build.log](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/2818868/tde-amarok-14.0.5-1-x86_64-build.log)
* [tde-gtk3-tqt-engine-14.0.5-1-x86_64-build.log](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/2818869/tde-gtk3-tqt-engine-14.0.5-1-x86_64-build.log)
* [tde-kmplayer-14.0.5-1-x86_64-build.log](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/2818870/tde-kmplayer-14.0.5-1-x86_64-build.log)
* [tde-systemsettings-14.0.5-1-x86_64-build.log](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/2818871/tde-systemsettings-14.0.5-1-x86_64-build.log)
* [tde-tdeedu-14.0.5-1-x86_64-build.log](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/2818873/tde-tdeedu-14.0.5-1-x86_64-build.log)

**Comment by SlavekB** [comment]
+ tdeartwork: Do you have TQt3 compiled with OpenGL support?
+ amarok: Do not use CMake – it's not complete and may not work. Use Automake.
+ gtk3-tqt-engine: Here is nothing to add – conversion for CMake has not yet begun == can not be build with CMake. Use Automake.
+ kmplayer: See commit [14c2f09f25](https://mirror.git.trinitydesktop.org/gitea/TDE/kmplayer/commit/14c2f09f25ba9462d8624e99ea853d1eb22d74e1)
+ tde-systemsettings: Do not use CMake – it's not ready and can not work. Use Automake.
+ tdeedu: See commit [a62993c00b](https://mirror.git.trinitydesktop.org/gitea/TDE/tdeedu/commit/a62993c00bdc57a1ae93e8016382fe0ca3e635d1)

**Comment by michael-manley** [comment]
Everything except tdeartwork and gtk3-tqt-engine dosnt build atm

#1 how would i enable opengl support.
#2 new log posted with errors
[tde-gtk3-tqt-engine-14.0.5-1-x86_64-build.log](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/2819217/tde-gtk3-tqt-engine-14.0.5-1-x86_64-build.log)
