### ISSUE TITLE
Out of date 10.0.6 now

### ISSUE THREAD

**Issue by michael-manley** [michael-manley/Trinity_ArchLinux_PKGBUILD#40]

**Comment by michael-manley** [comment]
Seems source packages are not yet released yet for 14.0.6, but will setup system with 14.0.5 to make porting easier

**Comment by Vistaus** [comment]
The sources for 14.0.6 are available now :)

**Comment by michael-manley** [comment]
>The sources for 14.0.6 are available now :)

@Vistaus yep i saw ill get started on it today getting the packages rebuilt

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikedebian** [comment]
Any progress on the effort on getting the packages built?

**Comment by Vistaus** [comment]
@michael-manley Still working on it? :)

**Comment by Vistaus** [comment]
Any update on this?

**Comment by hmtheboy154** [comment]
I think he may skip to R14.0.7 🤔
Because I talked to a Trinity dev and he said that R14.0.7 will release next month 🤔

**Comment by Vistaus** [comment]
> I think he may skip to R14.0.7 
> Because I talked to a Trinity dev and he said that R14.0.7 will release next month

Awesome! Didn't know they were dropping a new release so soon! Thanks for sharing! :) Hope Michael will still update us to 14.0.6, but waiting for 14.0.7 is also fine with me as long he doesn't take too long :yum: (jk, I know it's all volunteer work)
