### ISSUE TITLE
dcopserver won't start: Trinity session doesn't work

### ISSUE THREAD

**Issue by Vistaus** [michael-manley/Trinity_ArchLinux_PKGBUILD#42]
After modifying tde-tdebase to include gnu-free-fonts, I got your packages to work. However, when I try to start the Trinity session, it says "Check that dcopserver is running" and crashes the session. So the Trinity session doesn't work :(

Can you please help me solve this issue?

**Comment by SlavekB** [comment]
I think you have come across this problem:
http://bugs.pearsoncomputing.net/show_bug.cgi?id=3027

**Comment by Vistaus** [comment]
Thanks :) Downgrading libice solved the issue! But it still doesn't fully work: just abut everything works, but the sound server crashes upon login. Do you have a solution for that as well? :)
