### ISSUE TITLE
tde-tdebindings - /usr/bin/ld: cannot find -ltqt-mt and build{} requires "make -j1" and include ruby-2.2

### ISSUE THREAD

**Issue by thx1111** [michael-manley/Trinity_ArchLinux_PKGBUILD#5]
Building tde-tdebindings gives an error, "/usr/bin/ld: cannot find -ltqt-mt".

How does the linker NOT search in /opt/trinity/tqt3/lib/?

Despite having in the PKGBUILD
  ./configure \
...
    --with-qt-libraries=${QTDIR}/lib \
...

where /etc/profile.d/tqt3.sh has
export QTDIR=/opt/trinity/tqt3

and where there is
$ ldconfig -p |grep tqt-mt
        libtqt-mt.so.3 (libc6,x86-64) => /opt/trinity/tqt3/lib/libtqt-mt.so.3
        libtqt-mt.so (libc6,x86-64) => /opt/trinity/tqt3/lib/libtqt-mt.so

in tdebindings/dcopjava/binding, "make" generates the following command, where I have manually added the "-Xlinker --verbose",

$ g++ -Xlinker --verbose -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/crti.o /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/crtbeginS.o  .libs/client.o   -Wl,-rpath -Wl,/opt/trinity/lib -Wl,-rpath -Wl,/opt/trinity/tqt3/lib -Wl,-rpath -Wl,/opt/trinity/lib/trinity -L/opt/trinity/lib /opt/trinity/lib/libDCOP.so /opt/trinity/lib/libtdeui.so -ltqt-mt -lpng -lz -lXext -lX11 -lSM -lICE /usr/lib/libtqt.so -lpthread /opt/trinity/lib/libkjs.so /opt/trinity/lib/libtdefx.so /opt/trinity/lib/libtdecore.so -L/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0 -L/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/crtendS.o /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib/crtn.o  -O2 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro   -Wl,-soname -Wl,libjavadcop.so -o .libs/libjavadcop.so

with the result, for the sake of brevity, ld never searches in /opt/trinity/tqt3/lib, giving then,
/usr/bin/ld: cannot find -ltqt-mt
collect2: error: ld returned 1 exit status

I expect that this is a Trinity bug, rather than a PKGBUILD problem.

Just to see what happens, adding "${QTDIR}/lib" to "./configure ... --with-extra-libs=..." makes no difference.

As I understand, the  "-Wl,/opt/trinity/tqt3/lib"  and "-Wl,/opt/trinity/lib/trinity"  switches are not properly formatted, since a bare "/opt/trinity/lib/trinity" is not a proper option, and it is not an object file, to be passed to ld.  It all looks a mess to me, but I suppose that is a separate issue, to do with GNU autotools.

Looking at
/var/build/tde-tdebindings/src/tdebindings/dcopjava/binding/Makefile.am

I suspect that
libjavadcop_la_LDFLAGS = $(KDE_LDFLAGS) $(KDE_PLUGIN) -lDCOP -ltdecore -ltdeui $(LIB_QT) -lkjs -ltdefx

should instead be
libjavadcop_la_LDFLAGS = $(QT_LDFLAGS) $(KDE_LDFLAGS) $(KDE_PLUGIN) -lDCOP -ltdecore -ltdeui $(LIB_QT) -lkjs -ltdefx

which produces a working Makefile, but also will require a patch file.

Caution: there is a trailing "space" in the qt_ldflag.patch file on the line
-libjavadcop_la_SOURCES = client.cpp 

Also, unfortunately, the PKGBUILD build{} function requires "make -j1", or it will begin generating errors after entering tdebindings/smoke/tqt.

Also, tdebindings/qtruby/rubylib/qtruby/Qt.cpp references
# include <ruby.h>

where Arch has, from package ruby 2.3.0-2,
/usr/include/ruby-2.3.0/ruby.h

which can be added in the PKGBUILD,
--with-extra-includes="/usr/include/tqt:/usr/include/tqt/Qt:/usr/include/ruby-2.3.0" \

But then also, /usr/include/ruby-2.3.0/ruby.h references
# include "ruby/config.h"

where ls /usr/include/ruby-2.3.0/ gives only
ruby  ruby.h  x86_64-linux

and ls /usr/include/ruby-2.3.0/x86_64-linux/ has ruby/config.h.  This can also be added in the PKGBUILD, but now, it is going to be architecture dependent, with the subdirectory name being either i686-linux or x86_64-linux.  This becomes /usr/include/ruby-2.3.0/${CARCH}-linux.

Except, it is then seen that TDE R14.0.3 is NOT compatible with the current ruby 2.3.0, but only with ruby 2.2!!  The release notes declare "Added ruby 2.2 support".

So, install ruby2.2 2.2.4-1 from the AUR, and instead, add to the --with-extra-includes=,
/opt/ruby2.2/include/ruby-2.2.0:/opt/ruby2.2/include/ruby-2.2.0/${CARCH}-linux/

But even then, this results in many new errors, beginning 
make[5]: Entering directory '/var/build/tde-tdebindings/src/tdebindings/qtruby/rubylib/qtruby'
...
Qt.cpp:123:95: error: ambiguating new declaration of ‘void rb_str_catf(VALUE, const char_, ...)’
 void rb_str_catf_1(VALUE self, const char *format, ...) **attribute** ((format (printf, 2, 3)));
                                                                                               ^
In file included from /opt/ruby2.2/include/ruby-2.2.0/ruby.h:33:0,
                 from Qt.cpp:49:
/opt/ruby2.2/include/ruby-2.2.0/ruby/intern.h:702:19: note: old declaration ‘VALUE rb_str_catf(VALUE, const char_, ...)’
 PRINTF_ARGS(VALUE rb_str_catf(VALUE, const char*, ...), 2, 3);
                   ^
/opt/ruby2.2/include/ruby-2.2.0/ruby/ruby.h:47:3: note: in definition of macro ‘PRINTF_ARGS’
   decl **attribute**((format(printf, string_index, first_to_check)))
   ^
...

At this poing, for the moment, I give up.  These look like TDE bugs, and I am at a loss.

[qt_ldflags.patch.zip](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/190712/qt_ldflags.patch.zip)
[PKGBUILD.zip](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/190713/PKGBUILD.zip)

**Comment by michael-manley** [comment]
Humm, this is strange as I was able to build tdebindings fine. Wonder if its yet another missing dependency?

**Comment by thx1111** [comment]
What version, or versions, of Ruby did you have installed?  Or any?  The configure script did not have a switch to disable Ruby support, but I did not try uninstalling all Ruby packages to see what would happen.

**Comment by Ybalrid** [comment]
This package builds fine on a mostly barebone installation of Arch. `pacamn -Qs ruby` returns nothing so I don't have ruby installed...

**Comment by michael-manley** [comment]
On my builds I didn't have ruby installed.

**Comment by thx1111** [comment]
On my system, all of the current-version ruby 2.3 dependencies are optional.  So it would be simple enough to uninstall the ruby package, and not install the AUR ruby2.2 package, while building Trinity, and then re-install ruby.

Still annoying, when Trinity claims to support ruby 2.2, since there is no direct way to fix this from the PKGBUILD.  I will file a Trinity bug report.

And, what happened to the "make -j1" issue and "/opt/trinity/tqt3/lib/" location issue?

My "/opt/trinity/tqt3/lib/" location issue occurred in
/var/build/tde-tdebindings/src/tdebindings/dcopjava/binding
which is not ruby related, but is java related.  Did you build with java installed?

On my system, I was building with at quad-core processor.  Were you building on a system with fewer cores?  I encountered errors in
 /var/build/tde-tdebindings/src/tdebindings/smoke/tqt
so this does not seem to be ruby related, but uses perl.  Did you build with perl installed?

**Comment by thx1111** [comment]
BTW, I see that "make -j1" is a known issue for tdebindings, at
https://wiki.trinitydesktop.org/How_to_Build_TDE_Core_Modules#Notes_2
though they do add that "some people have no problems with this package and parallel processing".  I suspect that that has to do with just how much "parallel" is going on.  But that might have to do with whether tdebindings is being built without perl.

**Comment by thx1111** [comment]
Ok, I managed to build tdebindings with Ruby 2.3 with a little help from  Slávek Banko at the TDE.  First, I had left out the correct ruby directories from "--with-extra-libs=", but then also, the files
qtruby/rubylib/qtruby/configure.in.in
korundum/rubylib/korundum/configure.in.in
have to be patched to test explicitly for the presence of ruby 2.3 so that
#define HAVE_RUBY_1_9 1
is set in config.h.

And, and as discussed in Issue #2, the PKGBUILD was changed to explicitly set the environment variables.

Altogether, patching three files, setting the environment variables explicitly in the PKGBUILD, setting --with-extra-includes= and --with-extra-libs= for the current ruby version, tdebindings builds successfully with ruby support.

I've attached "configure.patch" and the resulting PKGBUILD.
[configure.patch.zip](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/195076/configure.patch.zip)
[PKGBUILD.zip](https://github.com/michael-manley/Trinity_ArchLinux_PKGBUILD/files/195081/PKGBUILD.zip)

**Comment by thx1111** [comment]
It has been pointed out to me that the standard environment variables for building TDE packages are just those described here:
https://wiki.trinitydesktop.org/How_to_Build_TDE_Core_Modules#Building_Packages_with_Autoconf

cp -Rp <path to your system's libtool.m4 file> admin/libtool.m4.in
cp -Rp <path to your system's ltmain.sh file> admin/ltmain.sh
make -f admin/Makefile.common

Configure and Build
export PREFIX=/opt/trinity
export SYSCONFDIR=/etc/trinity
export LIBDIR=/opt/trinity/lib
export MANDIR=/opt/trinity/man
export QTDIR=/opt/trinity/lib/qt3-3.3.8.d
export PATH=/opt/trinity/qt3-3.3.8.d/bin:/opt/trinity/bin:$PATH
export LD_LIBRARY_PATH=/opt/trinity/lib:/opt/trinity/lib/trinity:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=:/opt/trinity/lib/pkgconfig:/opt/trinity/qt3-3.3.8.d/lib/pkgconfig:$PKG_CONFIG_PATH
# Enable only one of the following:
# export DEBUG_AUTOTOOL_OPT="--enable-debug=full"
export DEBUG_AUTOTOOL_OPT="--disable-debug"

It is hard to know sometimes what environment variables have been set for superstitious or historic reasons, and which are actually necessary without some trial and error.  And we know that TDE has been moving from Autotools to CMake.

I also am not sure about the scope of variables set with makepkg.  Does it run commands in a subshell?  Do the set variables need to be explicitly unset to avoid contaminating the command-line shell environment?  When is "export" required?

I suppose there should be a TDE "group", or a couple of groups, to simplify building the package set.  I also think there should be some better use of prepare{} and build{} functions to support "makepkg --nobuild" and "makepkg --noextract".  I think of "prepare" as including running "configure" or "cmake", where "make" is then run from build{}.

**Comment by e1z0** [comment]
After I removed jre from the system, the problem was solved and everything compiled ok.
