### ISSUE TITLE
nasutek files don't exist anymore

### ISSUE THREAD

**Issue by danwdart** [michael-manley/Trinity_ArchLinux_PKGBUILD#51]
e.g.: http://repo.nasutek.com/arch/contrib/docker-dev/htdig-3.2.0b6-11-x86_64.pkg.tar.xz

**Comment by michael-manley** [comment]
I will take care of this today i just need to move the files to the new server.

**Comment by michael-manley** [comment]
I fixed the packages and can be downloaded again

**Comment by danwdart** [comment]
Awesome
